'use client';

interface NumberBadgeProps {
  value: number | string;
  source: 'user-provided' | 'app-calculated' | 'ai-estimated';
  label?: string;
  isCurrency?: boolean;
  suffix?: string;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export default function NumberBadge({
  value,
  source,
  label,
  isCurrency = true,
  suffix = '',
  size = 'md',
  className = '',
}: NumberBadgeProps) {
  const formattedValue =
    typeof value === 'number'
      ? isCurrency
        ? `₹${value.toLocaleString('en-IN')}`
        : value.toLocaleString('en-IN')
      : value;

  const sourceConfig = {
    'user-provided': {
      border: 'border-blue-500/30 dark:border-blue-400/20 bg-blue-50/60 dark:bg-blue-950/30 text-blue-900 dark:text-blue-200',
      tagBg: 'bg-blue-500 text-white',
      tagText: 'Your Input',
      icon: '✍️',
      description: 'Value entered directly by you',
    },
    'app-calculated': {
      border: 'border-emerald-500/30 dark:border-emerald-400/20 bg-emerald-50/60 dark:bg-emerald-950/30 text-emerald-900 dark:text-emerald-200',
      tagBg: 'bg-emerald-600 text-white',
      tagText: 'Calculated',
      icon: '⚙️',
      description: 'Computed accurately by deterministic financial formulas',
    },
    'ai-estimated': {
      border: 'border-saffron-500/30 dark:border-saffron-400/20 bg-saffron-50/60 dark:bg-saffron-950/30 text-saffron-900 dark:text-saffron-200',
      tagBg: 'bg-saffron-500 text-white',
      tagText: 'AI Insight',
      icon: '✨',
      description: 'Qualitative projection generated by ArthaSetu AI',
    },
  };

  const current = sourceConfig[source];

  return (
    <div
      className={`
        inline-flex flex-col rounded-2xl border p-3 transition-all
        ${current.border}
        ${className}
      `}
      title={current.description}
    >
      {/* Top row: Label + Source tag */}
      <div className="flex items-center justify-between gap-2 text-[10px] uppercase tracking-wider font-semibold opacity-80">
        <span className="truncate">{label}</span>
        <span className={`px-1.5 py-0.5 rounded-full text-[9px] font-bold ${current.tagBg} shrink-0`}>
          {current.icon} {current.tagText}
        </span>
      </div>

      {/* Main value */}
      <div className={`
        font-black tracking-tight mt-1 text-foreground
        ${size === 'sm' ? 'text-base' : size === 'lg' ? 'text-2xl sm:text-3xl' : 'text-xl sm:text-2xl'}
      `}>
        {formattedValue}
        {suffix && <span className="text-xs font-normal opacity-70 ml-1">{suffix}</span>}
      </div>
    </div>
  );
}
